version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - 8080:80

  app1:
    container_name: app1
    build: ./app1
    ports:
    - 5001:5000

  app2:
    container_name: app2
    build: ./app2
    ports:
    - 5002:5000